development:
  adapter: postgresql
  encoding: unicode
  database: lyon_development
  pool: 10
  username:
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: lyon_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: lyon_production
  pool: 5
  username:
  password:
